export const canvas = document.getElementById("cnv");
export const spanTime = document.getElementById("worldTime");
export const spanMouse = document.getElementById("mousePos");
export const spanPlayer = document.getElementById("playerPos");
export const divTerminal = document.getElementById("terminal");
export const divLog = document.getElementById("log");
export const commandLine = document.getElementById("commandLine");
export const divMap = document.getElementById("divMap");
export const spanWorldPos = document.getElementById("worldPos");
//# sourceMappingURL=htmlElements.js.map